spring:
  flyway:
    locations: classpath:db/migration/order,classpath:db/migration/inventory
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  mvc:
    apiversion:
      use:
        header: X-API-Version
      required: true
